######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 13 17:19:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += include/mainwindow.h \
           include/RenderWindow.h 
SOURCES += src/main.cpp \
           src/mainwindow.cpp \
           src/RenderWindow.cpp 
RESOURCES += EffectEditor.qrc
