//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MGRobot.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VIEW_ITEM                   101
#define IDD_ITEM_VIEW                   101
#define IDD_MGROBOT_DIALOG              102
#define IDD_MAIN_VIEW                   103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_LOGIN                130
#define IDD_DIALOG_DELETE_CONFIRM       131
#define IDD_DIALOG_OPERATE              132
#define IDD_DIALOG_                     133
#define IDD_DIALOG_CAMPAIGN             133
#define IDD_NEW_MAIN_VIEW               135
#define IDD_DLG_SETTING                 136
#define IDD_DLG_ONCE_OP                 137
#define IDD_DLG_REPEATEDLY_ORDER_OP     138
#define IDD_DLG_REPEATEDLY_RANDOM_OP    139
#define IDD_CAMPAIGN_OP                 140
#define IDC_STATIC_SHEET_RECT           1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_ACCOUNT_NAME           1001
#define IDC_EDT_PORT                    1001
#define IDC_EDT_MOVE_JIANGE_OP1         1001
#define IDC_EDT_MOVE_INTERVAL_OP1       1001
#define IDC_EDT_CAMP_NUM                1001
#define IDC_RICHEDIT21                  1002
#define IDC_EDIT_ACCOUNT_PSW            1002
#define IDC_EDIT_MEMBER_COUNT_PRE       1002
#define IDC_EDT_ACCOUNT                 1002
#define IDC_EDIT2                       1002
#define IDC_EDT_MOVE_CYCLE_LIFE_OP1     1002
#define IDC_EDT_CAMP_GENERAL_NUM        1002
#define IDC_COMBO_SERVER                1003
#define IDC_EDIT_CAMPAIGN_ID            1003
#define IDC_EDT_ACCOUNT_START           1003
#define IDC_EDT_CAMP_TIMEOUT            1003
#define IDC_BUTTON_ADD_ACOUNT           1004
#define IDC_EDIT_ROOM_MASTER            1004
#define IDC_EDT_ACCOUNT_END             1004
#define IDC_LIST_ACCOUNT                1005
#define IDC_EDIT_MENBER_COUNT           1005
#define IDC_COMBO_CLAN                  1006
#define IDC_EDIT_CAMPAGIN_COUNT         1006
#define IDC_EDT_PSW                     1006
#define IDC_BUTTON_DELETE_ACCOUNT       1007
#define IDC_BUTTON_SAVE                 1008
#define IDC_BUTTON_READ                 1009
#define IDC_BUTTON_ACCOUNT_LOGIN        1010
#define IDC_BUTTON_CREATE_CLAN          1011
#define IDC_BUTTON_CREATE_CHARACTER     1012
#define IDC_BUTTON_JOIN_GAME            1013
#define IDC_BUTTON_AUTO_JOIN_GAME       1015
#define IDC_CHECK_USE_SKILL             1015
#define IDC_STATIC_STATE                1016
#define IDC_CHECK_JUMP_MAP              1016
#define IDC_BUTTON_TOTAL_COUNT          1017
#define IDC_CHECK_TEST_NET              1017
#define IDC_BUTTON_SELECTED_COUNT       1018
#define IDC_CHECK_RAND_TEST             1018
#define IDC_CHECK_USE_SKILL2            1018
#define IDC_BUTTON_CHECK_COUNT          1019
#define IDC_CHECK_ORDER_TEST            1019
#define IDC_BUTTON_DEL_CLAN             1020
#define IDC_BUTTON_NOW_COUNT            1020
#define IDC_CHECK_TEST_RANDMOVE         1020
#define IDC_BUTTON_DEL_CHARACTER        1021
#define IDC_BUTTON_DEL_CANCLE           1021
#define IDC_BUTTON_CLOSE_ALL            1022
#define IDC_STATIC_TOTAL_COUNT          1022
#define IDC_STATIC_SELECTED_COUNT       1023
#define IDC_STATIC_CHECK_COUNT          1024
#define IDC_STATIC_NOW_COUNT            1025
#define IDC_BUTTON1                     1026
#define IDC_STATR_OPERATE               1026
#define IDC_BTN_STATR_OPERATE           1026
#define IDC_BTN_CREATE_CAMPAGIN         1026
#define IDC_BTN_CONNECT_LOGIN           1026
#define IDC_BTN_SETSETTING              1026
#define IDC_BTN_CAMP_SETTING            1026
#define IDC_BUTTON_CLEAR_MESSAGE        1027
#define IDC_BUTTON2                     1027
#define IDC_END_OPERATE                 1027
#define IDC_BTN_END_OPERATE             1027
#define IDC_BTN_DESTORY_CAMPAGIN        1027
#define IDC_BTN_SENDDATA_TO_LOGIN       1027
#define IDC_RM_START                    1027
#define IDC_BTN_ORDER_START_OP1         1027
#define IDC_BTN_RM_START                1027
#define IDC_CHECK_LOGIN                 1028
#define IDC_BTN_LOGIN_LOGIN             1028
#define IDC_RM_START_OP1                1028
#define DC_BTN_ORDER_END_OP1            1028
#define IDC_BTN_RM_START_OP1            1028
#define IDC_STATIC1                     1029
#define IDC_BTN_CONNECT_FRONT           1029
#define IDC_RM_END_OP1                  1029
#define IDC_BTN_RM_END_OP1              1029
#define IDC_STATIC2                     1030
#define IDC_BTN_SENDDATA_TO_FRONT       1030
#define IDC_RADIO_RAND_TEST             1031
#define IDC_BTN_LOGIN_FRONT             1031
#define IDC_RADIO_ORDER_TEST            1032
#define IDC_BTN_ACCOUNT_LOGIN           1032
#define IDC_STATIC3                     1033
#define IDC_BTN_CREATE_CAN              1033
#define IDC_BTM_DEL_CLAN                1034
#define IDC_BTN_DEL_CLAN                1034
#define IDC_BTN_CREATESO                1035
#define IDC_BTN_CREATESOLDIER           1035
#define IDC_BTN_JIONGAME                1035
#define IDC_COMBO_CAN_CREATE            1036
#define IDC_BTN_CREATESOLDIER2          1036
#define IDC_COMB0_CREATED               1037
#define IDC_BTN_CREATE_CHARACHTER       1037
#define IDC_BTN_CLOSE_NET               1038
#define IDC_BUTTON3                     1039
#define IDC_BTN_STRAT_CAMPAGIN          1039
#define IDC_BTN_AUTO_JOINGAME           1039
#define IDC_BTN_ORDER_START             1039
#define IDC_BTN_FLASH                   1039
#define IDC_BTN_REFLASH                 1039
#define IDC_CHECK_TEST_LOGINANDOUT      1040
#define IDC_BTN_RANDOM_MOVE             1040
#define IDC_CHECK2                      1041
#define IDC_CHECK_TEST_CREATECAM        1041
#define IDC_BTN_TEST_SKILL              1041
#define IDC_EDIT_RANDMOVETIME           1042
#define IDC_BTN_CREATE_CAMP             1042
#define IDC_EDIT_MAPID                  1043
#define IDC_EDIT_RANDMOVETIME2          1043
#define IDC_EDIT_SEND_SIZE              1043
#define IDC_BTN_START_ONCE_OP           1043
#define IDC_TEST_LOGIN_NET              1046
#define IDC_CHECK_FULLSERVER_CHAT       1047
#define IDC_CHECK_REGION                1048
#define IDC_CHECK_REGION_CHAT           1048
#define IDC_STATIC_SHEET_RECT1          1051
#define IDC_IP_SERVER                   1052
#define IDC_EDT_LOGINDATA_SIZE          1053
#define IDC_EDT_FRONTDATA_SIZE          1054
#define IDC_LIST_ACCOUNT1               1055
#define IDC_CHK_RANDOM_MOVE_OP1         1056
#define IDC_CHK_AUTOJOINGAEM_ORDER_OP1  1057
#define IDC_CHK_MOVE_ORDER_OP1          1058
#define IDC_CHK_CLOSE_ORDER_OP1         1059
#define IDC_COMBO1                      1061
#define IDC_COMBO2                      1062
#define IDC_COMBO3                      1063
#define IDC_COMBO4                      1064
#define IDC_EDIT4                       1065
#define IDC_CHK_SENDPACKET_LOGIN_OP1    1066
#define IDC_EDT_SENDPACKET_LOGIN_INTERVAL_OP1 1067
#define IDC_EDIT5                       1068
#define IDC_EDIT6                       1069
#define IDC_EDIT7                       1070
#define IDC_EDIT8                       1071
#define IDC_EDIT9                       1072
#define IDC_EDT_SENDPACKET_FRONT_SIZE_OP1 1072
#define IDC_CHK_SENDPACKET_FRONT_OP1    1073
#define IDC_EDT_SENDPACKET_FRONT_INTERVAL_OP1 1074
#define IDC_EDT_SENDPACKET_LOGIN_CYCLE_LIFE_OP1 1075
#define IDC_EDT_SENDPACKET_FRONT_CYCLE_LIFE_OP1 1076
#define IDC_EDT_SENDPACKET_LOGIN_SIZE_OP1 1077
#define ID_32771                        32771
#define ID_32772                        32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
