######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 13 17:19:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += include/mainwindow.h \
           include/RenderWindow.h \
	   include/EntityWidget.h \
	   include/EffectWidget.h \
 	   include/EventWidget.h \
	   include/TimeLineWidget.h \
	   include/TimeLineWindow.h \
	   include/SlidersGroup.h \
	   include/AddObjectTabDialog.h \
	   include/AddEventDlg.h \
	   include/ExModelWidget.h \
	   include/ExComponentWidget.h \
	   include/ModelVisibleProWidget.h \
	   include/ModelAniProWidget.h \
	   include/ModelBindProWidget.h \
	   include/PUStartProWidget.h \
	   include/PUStopProWidget.h \
	   include/PUBindProWidget.h \
	   include/WeaponLightProWidget.h \
	   include/EffectFadeProWidget.h
SOURCES += src/main.cpp \
           src/mainwindow.cpp \
           src/RenderWindow.cpp \
           src/EntityWidget.cpp \
	   src/EffectWidget.cpp \
	   src/EventWidget.cpp \
	   src/TimeLineWidget.cpp \
	   src/TimeLineWindow.cpp \
	   src/SlidersGroup.cpp \
	   src/AddObjectTabDialog.cpp \
	   src/AddEventDlg.cpp \
	   src/ExModelWidget.cpp \
	   src/ExComponentWidget.cpp \
	   src/ModelVisibleProWidget.cpp \
	   src/ModelAniProWidget.cpp \
	   src/ModelBindProWidget.cpp \
	   src/PUStartProWidget.cpp \
	   src/PUStopProWidget.cpp \
	   src/PUBindProWidget.cpp \
	   src/WeaponLightProWidget.cpp \
	   src/EffectFadeProWidget.cpp
RESOURCES += EffectEditor.qrc
